### ISSUE TITLE
Tool only imports 1st row in MW 1.24.1

### ISSUE THREAD

**Issue by pjatx** [kghbln/ImportUsers#6]
Confirmed that encoding was UTF-8 without BOM and tried with both 4 and 5 columns. Each time I try to import a CSV with many lines only the user in the first row is created.

**Comment by kghbln** [comment]
I cannot replicate this issue. Just imported a bunch of users on MW 1.24.1 using version 1.4.2 of this extension. Make also sure that you do not use any quoting for the text.

**Comment by pjatx** [comment]
I'm able to consistently reproduce on my side with MW 1.24.1 using version 1.4.2. What other information can I provide to be helpful?

Here's an example of what I'm trying to import (fields different of course in the real example). Anything else to be mindful of? 

firstname.lastname,password,firstname.lastname@domain.com, Firstname Lastname
firstname.lastname,password,firstname.lastname@domain.com, Firstname Lastname
firstname.lastname,password,firstname.lastname@domain.com, Firstname Lastname
firstname.lastname,password,firstname.lastname@domain.com, Firstname Lastname

**Comment by kghbln** [comment]
Probably you are either consistently doing the same mistake or running into the same error. I did exactly the same import which worked out perfect. Did you check if issue https://github.com/kghbln/ImportUsers/issues/2 applies? Also prefer OpenOffice or LibreOffice to generate the csv-file. Excel still can drive people nuts in this respect. I myself regularly fail to produce usable csv with Excel.

It is always good to provide the versions of PHP, MYSQL etc. What was the last version working for you? Things like that. See also the [help page on debugging](https://www.mediawiki.org/wiki/Manual:How_to_debug) for further information.

Generally this extension needs a complete overhaul, so there may very well be something in the water. Sadly I am not a coder either so I can only clarify and test. So far things work smoothly.

**Comment by vargatron** [comment]
I had the same problem with import aborting after the first row. I was using excel on a Mac to export the csv

I solved it by opening the file in Sublime Text and selecting from the top menu:
View > Line Endings > Unix

(original setting was on Mac Os9 ... an excel artifact?)
after I resaved the upload worked beautifully!

**Comment by pjatx** [comment]
@vargatron awesome, thanks! Was totally using Excel for Mac as well. I never use it anymore for CSVs.
