### ISSUE TITLE
Message "action-import_users" missing

### ISSUE THREAD

**Issue by kghbln** [kghbln/ImportUsers#9]
The following message still has to be added:

`"action-import_users": "import users into this wiki"` which fills in for ... in

"You do not have permission to ...".

@dorozynskij Perhaps you could drop the Polish translation for this as a new post to this issue

**Comment by dorozynskij** [comment]
Sure, I can :-)
"action-import_users": "importowania użytkowników do tej wiki"
and
"You do not have permission to ..." will be "Nie masz uprawnień do ..."

**Comment by kghbln** [comment]
Great. Thank you. The fist part of the message is provided by MediaWiki core though.

**Comment by kghbln** [comment]
Done with pull request https://github.com/kghbln/ImportUsers/pull/10 Thank you Ency, 1.5.2 is out now.
